# Generated by Django 4.2.27 on 2025-12-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("start_date", models.DateTimeField()),
                ("venue_name", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("event_url", models.URLField(blank=True, max_length=500, null=True)),
                ("source", models.CharField(max_length=50)),
                ("raw_payload", models.JSONField()),
                (
                    "fingerprint",
                    models.CharField(
                        blank=True,
                        help_text="Deterministic hash used to deduplicate records without URLs.",
                        max_length=64,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date", "title"],
                "indexes": [
                    models.Index(fields=["city"], name="event_city_idx"),
                    models.Index(fields=["start_date"], name="event_start_date_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                condition=models.Q(("event_url__isnull", False)),
                fields=("source", "event_url"),
                name="event_unique_source_url",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("event_url__isnull", True), ("fingerprint__isnull", False)
                ),
                fields=("source", "fingerprint"),
                name="event_unique_source_fingerprint",
            ),
        ),
    ]
