# Generated by Django 4.2.27 on 2025-12-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
